metadata:
  name: erl_ip_index
  description: "erlang library of ip addresses."
  labels:
    jira-project: DEGA
    jira-board: 189
  links:
    - url: https://github.com/adgear/erl_ip_index/blob/master/README.md
      title: Component Documentation Page
spec:
  owner: cg-dsp-bidding-systems
  type:  library
  lifecycle: production
