name: Erlang CI
on: push
jobs:
  Run:
    strategy:
      matrix:
        erlang: ['24', '25', '26']
    runs-on: ubuntu-latest
    container:
      image: erlang:${{ matrix.erlang }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        env:
          cache-name: rebar3
        with:
          path: |
           ~/.cache/rebar3
          key: ci-${{runner.os}}-${{env.cache-name}}-erlang_${{matrix.erlang}}-rebar3-${{hashFiles('rebar.lock')}}
          restore-keys: |
            ci-${{runner.os}}-${{env.cache-name}}-erlang_${{matrix.erlang}}-rebar3
            ci-${{runner.os}}-${{env.cache-name}}-erlang_${{matrix.erlang}}
      - name: check
        run: make check